spring:
  output:
    ansi:
      enabled: ALWAYS

springdoc:
  api-docs:
    path: /openapi-docs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8766/eureka/
abdu:
  yml: hello world from yaml file
