spring:
  output:
    ansi:
      enabled: ALWAYS

springdoc:
  api-docs:
    path: /openapi-docs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/addressdb
    username: root
    password: abdulkwm
  jpa:
    hibernate:
      ddl-auto: create

abdu:
  name: "Hello World!"
